drone/drone-ui

- .gitignore
- README.md
- docker-compose.yml
Right now it's not that great to get started with the UI development.
I took the time to write a `docker-compose.yml` with `gogs:latest` and `drone:0.5`.
Sadly it's not working a 100% because the gogs container can't find the drone container to push webhooks... If anyone has an idea, please let me know!
Also to test the websocket implementation, one needs the current master from github.com/bradrydzewski/drone which isn't available as docker image, right @bradrydzewski ?
> Create a development environment with docker

- README.md
> Adjust cli option and add dependency

- webpack.devserver.js
Still not sure if this really fixes the problem, but I have to leave now. At least the 101 protocol update is now working.
> fix websocket proxying for dev

- webpack.devserver.js
@bradrydzewski This should fix the crashing and hopefully the WDS is finally working as expected 🙏
> fix webpack-dev-server crashes

- .drone.yml
- .eslintrc.yml
- src/actions/events.js
- src/components/build_meta.js
- src/components/build_panel.js
- src/components/job_list_item.js
- src/components/layout/breadcrumb.js
- src/components/layout/header.js
- src/components/layout/page.js
- src/components/repo_list_item.js
- src/components/term.js
- src/components/term_row.js
- src/pages/build/content.js
- src/pages/build/index.js
- src/pages/build/log.js
- src/pages/build/results.js
- src/pages/dashboard/content.js
- src/pages/dashboard/header.js
- src/pages/repository/content.js
- src/pages/repository/header.js
- src/pages/repository/index.js
- src/pages/repository/sidebar.js
- src/pages/repository/toolbar.js
- src/pages/repository_badge/content.js
- src/pages/repository_settings/content.js
- src/pages/user_profile/content.js
- src/pages/user_profile/header.js
- src/pages/user_profile/sidebar.js
- src/routes.js
Such commits are annoying I know, but better start with it earlier than later 😄 
See #15
> Fix eslint errors

- src/components/build_meta.js
> Alternate build history item description based on event type

- src/components/build_card.js
- src/components/build_card.less
- src/components/build_panel.js
- src/components/build_panel.less
This PR addresses https://github.com/drone/drone-ui/issues/68. Feedback/suggestions welcome.
> WIP! Adds parent build href in the UI

- src/components/build_meta.js
- src/components/build_meta.less
> Adds time information for each build history item

- package.json
- src/actions/events.js
- src/actions/tree.js
- src/pages/repository/content.js
- src/pages/repository/index.less
- src/utils/filter.js
This (WIP) PR is related to enhancement proposal raised in https://github.com/drone/drone-ui/issues/63. Would be good to get some feedback on this.
Screencast:
> Adds repo build history filtering by base attributes

- src/actions/events.js
- src/actions/tree.js
- src/components/build_panel.js
- src/components/job_list_item.js
- src/components/status.js
- src/components/term.js
- src/components/term.less
- src/components/term_row.js
- src/pages/build/content.js
- src/pages/build/matrix.js
- src/pages/build/results.js
- src/pages/repository/content.js
- src/pages/repository/index.less
this pull request provides support for https://github.com/drone/drone/pull/1981. Note there are definitely some rough edges that will need to be smoothed out and some non-essential features that were disabled and need to be fixed / re-enabled
> upgrade to per-step build output

- src/actions/events.js
Add missing parameter in function.
Closes https://github.com/drone/drone-ui/issues/102
> Fix collapse in build page.

- src/actions/events.js
- src/actions/tree.js
- src/pages/repository/sidebar.js
if no repos are enabled it leaves Loading up.  This will show a diff notification while loading vs none being enabled.
> Show no repos enabled if results have returned with nothing

- src/actions/events.js
Remove console log (maybe used for debug?)
> Remove console.log

- package.json
- src/pages/repository_settings_secret/content.js
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
> remove skip verify from UI.

- package.json
- src/screens/repo/screens/build/index.js
- src/shared/components/__tests__/status.test.js
- src/shared/components/status.js
- src/shared/constants/status.js
- src/shared/utils/build.js
- src/shared/utils/proc.js
Replace constant as string with const definition in codebase.
> Uppercase status const and use them in codebase

- src/shared/components/status.js
Fixed regression introduced with #159
> Fix status label in build page (see #159)

- src/shared/components/status.less
- src/shared/components/status_number.less
Closes #162
Identify pending build with gray color:
> refs #162: pending build are identified by gray color

- .github/issue_template.md
Remove traces of deprecated gitter channel
> Update issue_template.md [CI Skip]

- src/components/RepoItemLabel.vue
> Show promotion target in build activity feed

- src/components/pages/build/log-view/console-manager/console-manager.jsx
- src/components/pages/build/log-view/console-manager/console-manager.state.js
- src/components/pages/build/log-view/console-manager/console-manager.utils.js
- src/components/pages/build/log-view/log-view.jsx
- fix that will surface build stage and build step error messages better
- clean up the eslint errors I saw along the way
> show error message for steps and stages

- package.json
- src/components/shared/activity/simple.jsx
- src/components/shared/activity/simple.module.scss
- Fixed the alt avatar bug
- Fixed linting errors in the file
- Updated lodash version
> fix off centre alt avatar bug

- src/components/shared/activity/simple.jsx
Fix the wrong field reference in the component `PullRequestActivity` to fix the branch link
> fix branch link bug

- src/pages/settings/general/general.jsx
- src/pages/settings/settings.jsx
- wrap general component in a callback hook
- add proptypes to settings and general components
> stop general settings from remounting on each new build

- src/hooks/swr/builds.js
due to some incorrect logic the repo builds page would never show more builds than the build count when the page was loaded - except for the first build
so if there was build number 3, 2 and 1 showing - then a new build was kicked off, the new builds would be 4, 3 and 2 - build 1 would be overwritten in the UI.
everything was fine in the backend, thats why, if the page was reloaded 4 builds would show :)
> fix builds stream event behaviour

- src/components/pages/repo/build-list/build-list.jsx
- src/components/pages/repo/new-build-form/new-build-form.jsx
- src/components/shared/bar-chart/bar-chart.jsx
- src/hooks/swr/builds.js
- src/hooks/swr/index.js
- src/pages/repo/repo.jsx
- push successful manually triggered builds to build list
- fix lint errors
- add proptypes to files I touched
> kicking off new build manually will push build to build list

- src/hooks/swr/index.js
- src/hooks/swr/use-org-secrets.js
- src/pages/settings/secrets/index.js
- src/pages/settings/secrets/org-secrets.jsx
- src/pages/settings/secrets/secrets.jsx
- src/pages/settings/secrets/shared.jsx
- src/pages/settings/settings.jsx
- src/pages/settings/settings.module.scss
Add org secrets page to repo settings
> Feat/dron 129 - Add org secrets page

- package-lock.json
- package.json
- src/hooks/swr/index.js
- src/hooks/swr/use-templates.js
- src/pages/settings/settings.jsx
- src/pages/settings/templates/index.js
- src/pages/settings/templates/templates.jsx
- src/pages/settings/templates/templates.module.scss
- Add template section to repo settings
- update react-scripts version
> add templates to repo settings

- package-lock.json
- src/hooks/store.js
- src/pages/home/home.jsx
- src/pages/home/home.module.scss
- Add ability to sort repos by recency or alphabetical title
- Add ability to filter by organisation
- Fix active toggle logic
> New filter and sort options for repo list

- README.md
Update to community information:
> add community/support information

- src/components/shared/elapsed/elapsed.jsx
> (fix) display durations longer than 24hrs

- src/pages/build/build.jsx
- src/pages/build/deployment-form/deployment-form.jsx
Didn't realize eslint wasn't automatically applied and pushed up some silly mistakes. Was able to render the page successfully locally with these fixes in.
> added missing import + fixed eslint
