drone/drone-ui

src/components/status.less

This then looks like this:
Before both icons for pending and running had the same color.

Provide different color for icon of pending jobs

---

src/actions/tree.js
src/pages/repository/toolbar.js

This restores active toolbar tab highlighting which was disabled in 9b40b6986db7fc986f0d9c1b3aa9adea7e423164, by using `this.props.location` injected by react-router instead of browser `window.location`.

Support Firefox 49 by using react-router provided location

---

src/pages/build/results.js

As discussed on gitter before, it's tedious to show the two buttons by clicking the bottom on the right. Instead show both buttons by default and make them hideable.

Open details for build by default to make following easier

---

src/pages/repository_settings/index.less

Before:
After:
Matches the appearance in Chrome now :)

Center slider thumb button in Firefox

---

src/components/layout/tabs.less

Center tab label in clickable area

---

src/components/layout/page.js
src/components/layout/page.less

The Drone logo isn't an avatar (isn't square). I've increased the top margin so that this matches the avatar margin on the right.
Before:
After:

Keep aspect ratio of Drone logo

---

src/components/repo_list_item.less

Very long repository names without characters like `-` won't word-break and therefore make the horizontal scroll-bar appear (and move the status icon down). After this PR `...` will be used to shorten the name in these cases.

Show ellipsis for long repo names

---

src/actions/events.js

The repo variable isn't available until https://github.com/jhasse/drone-ui/blob/4cb3de77305d8240e19ef644fd3951176aacd706/src/actions/events.js#L391
This fixes error messages not showing up when activating a repository in the account settings.

Don't use repo variable before it is available

---

src/pages/build/matrix.js

`BuildPanel` component is not being passed the `repo` props on matrix builds. This breaks the rending of matrix builds that are "forked" (i.e. has a parent).
Passing the props downstream fixes this bug.

fix rendering of matrix builds with parents (fork builds)

---

src/components/term_row.less

When there's a long string of characters without spaces in the build log, it falls off the edge of the page. Setting min-width to 0, per [this article](https://hackernoon.com/11-things-i-learned-reading-the-flexbox-spec-5f0c799c776b), allows these long strings to be wrapped.
Before:
After:

Allow output lines with long words to be broken

---

src/drone/drone-proc.html

Fixes https://github.com/drone/drone-ui/issues/132
So, this is *one* version of the fix. There is an alternative, which is arguably less desirable. The jist of the alternative solution is the following:
Change
```
<div class="term-row">
<div></div>
<div></div>
<div></div>
</div>
```
to
```
<div class="term-row"><div></div><div></div><div></div></div>
```
This alternative solution also hints at the problem (at least in Safari, maybe others?). HTML code formatting is counted when the parent has ```white-space: nowrap``` in Safari (luckily Chrome seems to understand how to handle this as expected). New lines and multiple spaces are honored, both of which can and do exist in the HTML output inside ```.term-row``` elements and messes with the flex layout.
This change moves the formatting rule …

(css) Fix .term-row styling issue

---

src/drone/drone-status.html

By offsetting the centre of rotation, the "wiggle" effect of the animation is mitigated.
I cannot be sure whether it is intentional that the wiggle effect is there however it has always annoyed me slightly.
If you'd rather leave it as is, for nostalgia sake or whatever, I can understand that.
Below is an example of before and after, zoomed in at 400% in Chromium v60. At 100% zoom it is much smoother and less 'wiggly'

Proposed 'pending' icon wiggle fix

---

src/shared/components/build_event.js

When there are deployment build `target` is missing

Add props that's needed in "deployment" build

---

src/screens/feed/components/list.less
src/shared/components/build_event.less
src/shared/styles/utils.less

Current interface, when branch name is long (eg using `feature/1234-implements-come-really-nice-feature-when-outside-the-window-rain`) generate inconsistency in UI, eg. in build list create row with different length in each build.
This PR ellipses text when branch name is too long to have consistency in visualization, if branch have "short" name full name is visibile, if branch name is too long it will truncate and text ellipsed. On my monitor branch with ~20 chars are fully visible, other are truncated.

Truncate long branch name

---

src/shared/components/drawer/drawer.less

In sidebar menu (eg in repositories page) when there are disabled button on mouse-hover the menu the background color is the same we have on text and we should not read content; his fix will change background color to make possible read button content, eg:
Current (no mouse hover):
Current (with mouse hover):
Fix (with mouse hover):

fix background color for disabled button in sidebar menu

---

src/screens/repo/screens/build/logs/components/term.less

Before:
After:
I think that ansi_up assumes a black terminal background and that's why it assigns a white color for "bold/bright". This results in compiler messages to be unreadable (see screenshot above).
I've swapped black and white and turned "bright" into bold. It isn't 100% correct (assigning the bold attribute shouldn't change the color), but this is the easiest fix without fixing ansi_up (which has other bugs too).
If you want I can also try to do #86 again.

Switch black and white since ansi_up assumes a dark terminal

---

src/screens/repo/screens/secrets/components/form.js
src/screens/repo/screens/secrets/components/form.less
src/screens/repo/screens/secrets/index.js

Default is left as it was before when adding from UI
Screenshot:

Allow to set events when adding new secret

---

src/components/RepoItem.vue

RepoItems attempt to display the entire commit message for each build
triggered by a commit. This is okay for most users as the message will
run out of space and be truncated. However, I among many others with
Hi-DPI displays have customized Drone's CSS to take up more monitor
space, which leads to some very ugly build names, as the RepoItem
displays the commit message and body.
This PR trims the title to just the first line of the commit message.

Truncate commit message to first line in RepoItem

---

src/views/Build.vue

Currently with large logs it takes many clicks to be able to see the
entire log file or the top of the log file.
This button displays all log lines with one click.

Add button to show all log lines

---

src/views/Build.vue

Currently, consecutive spaces are collapsed inside the build logs, which messes up alignment using them. Adding `white-space: pre-wrap` to the style prevents this behavior.
Note that unlike `pre`, `pre-wrap` does not prevent the proper line wrapping from happening.
fixes #253

Preserve whitespace in build logs

---

src/views/Build.vue

This should fix an issue where Firefox users were unable to download job logs.
https://github.com/drone/drone-ui/issues/300

Fix log download link in Firefox

---

src/views/Build.vue

Fixes #324
**Before:**
[![](https://user-images.githubusercontent.com/13909717/74612667-720e0900-50d5-11ea-9ae7-f5bc3559e2c1.png)](https://cloud.drone.io/geek1011/dictutil/64/7/6)
**After:**
@bradrydzewski

Disable font ligatures in build log

---

src/components/Search.vue

In Firefox, for some reason selecting an item with the mouse would not
clear the search overlay. It appears that it would generally clear when
the blur function is called, but something appears to be different when
selected by mouse vs enter key.
This forces a call to `this.close()` to close the dialog without relying
only on the blur action.
Fixes #263

Force close of search box after item selection

---

src/components/Stage.vue

Before:
After:
Notice the 'g' is cut-off because of `overflow: hidden` and not enough `line-height`, this fixes it.

Fix cut-off letter in stage name

---

public/index.html

I was tired of seeing "Web site created using create-react-app" when linking to builds etc.

Meta Description: Replace create-react-app text with Drone text

---

src/hooks/swr/builds.js

Bitbucket server allow users to create private repositories. The path looks like this: gitserver.company.com/~muffl0n/drone-test.git
This PR adds ~ as a allowed char in the project name

allow ~ in project name

---

src/components/pages/build/log-view/stage-nav/stage-nav.jsx

- Adds a simple tooltip to the build step button incase step title is too long for UI

add tooltip to long build step names

---

src/app.jsx
src/index.jsx
src/pages/builds/builds.jsx

strip trailing slash from url to fix build link bug

---

src/pages/build/build.jsx

Removing local storage of build tab to fix bug around the upcoming card tab only sometimes being present

remove local storage of build tab

---

src/pages/settings/general/general.jsx

non-admin user's ability to toggle repo protected status was removed as a a regression between v1 and v2 - this will fix that

allow non-admin user to toggle repo protected status

---

src/pages/build/deployment-form/deployment-form.module.scss

Fix controls button color in deployment form
**Current (light, dark)**
**Fixed (light, dark)**

fix: button display in deployment form
